# Generated by Django 3.1 on 2020-09-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='upload',
            field=models.ImageField(null=True, upload_to='airlines/'),
        ),
    ]
