# Generated by Django 3.1 on 2020-09-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airline_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='upload',
            field=models.ImageField(null=True, upload_to='static/airlines/'),
        ),
    ]
